---
- name: Setup Application Server
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache and install required packages
      apt:
        name:
          - openjdk-17-jdk
          - maven
        state: present
        update_cache: yes

    - name: Ensure app directory exists
      file:
        path: /home/ubuntu
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Clean up old application JAR
      file:
        path: /home/ubuntu/app.jar
        state: absent

    - name: Clean up old log file
      file:
        path: /home/ubuntu/app.log
        state: absent
