---
- name: Install Java 17 and Maven
  hosts: artifact_server,app_server
  become: yes
  tasks:
    - name: Update apt cache and install packages
      apt:
        name:
          - openjdk-17-jdk
          - maven
        state: present
        update_cache: yes
